
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[412] =
    {   0,
      111,  111,  120,  118,   80,   79,  117,   67,   72,   81,
      118,   84,   85,   69,   68,   90,   70,   89,   71,  112,
      112,   91,   88,   59,   93,   60,  111,   86,   87,   99,
      118,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,   82,   98,
       83,   63,  103,   65,  104,  102,    0,    0,   97,   74,
       77,   73,   78,   75,    0,  113,   96,   95,   76,  113,
      112,    0,    0,    0,    0,    0,    0,  114,  112,    0,
       92,  110,  101,   61,   64,   62,  100,  111,  111,    0,
      106,    0,  111,  111,  111,  111,  111,  111,  111,  111,

      111,  111,  111,  111,  111,  111,  111,   12,   14,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  105,    0,   66,  109,  115,    0,
      115,    0,    0,    0,    0,   94,  113,    0,    0,  113,
        0,  112,    0,    0,  112,    0,    0,  113,  112,    0,
        0,  112,    0,  112,    0,  108,  107,  111,  111,  111,
      111,   48,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,   10,  111,  111,  111,  111,   26,
       47,  111,   17,   49,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,   25,    0,    0,    0,

        0,    0,    0,  113,  113,    0,    0,  113,  112,    0,
      113,    0,  112,    0,    0,    0,  112,    0,    0,  111,
       42,   41,  111,    2,    3,  111,  111,  111,  111,   51,
      111,  111,  111,    8,  111,  111,  111,   11,   13,   56,
      111,  111,  111,  111,   27,  111,   46,  111,  111,  111,
       55,  111,  111,   43,  111,  111,  111,  111,   24,   31,
        0,    0,    0,    0,  113,    0,  113,    0,    0,    0,
        0,    0,  113,  111,    1,   52,  111,    4,  111,  111,
        7,  111,   45,  111,  111,  111,   28,   29,   30,  111,
      111,   57,   19,  111,  111,  111,  111,  111,  111,  111,

      111,  111,   32,  111,    0,    0,    0,    0,    0,    0,
      113,    0,   50,  111,  111,  111,   53,  111,  111,  111,
       15,  111,  111,  111,   20,   21,   44,  111,   23,   33,
       34,   35,  111,    0,    0,    0,   54,  111,  111,  111,
       37,   38,  111,   18,   58,   22,   36,    0,    0,    0,
      111,  111,    5,    6,  111,  111,    0,    0,    0,  111,
       39,  111,   16,    0,    0,    0,   40,  111,    0,    0,
      111,    0,    0,    9,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  116,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   24,   26,   27,   28,   29,   30,
       31,   32,    7,    7,   33,   34,   35,   36,   37,   36,
       38,   38,   39,   38,   38,   38,   38,   38,   40,   41,
       38,   38,   42,   38,   43,   44,   38,   45,   38,   38,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   38,   61,   62,   63,   64,
       65,   66,   38,   67,   68,   69,   70,   71,   72,   73,
       74,   38,   75,   76,   77,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[78] =
    {   0,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    3,    2,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    2,    2,    2,
        2,    2,    5,    5,    5,    5,    6,    7,    7,    7,
        8,    7,    7,    7,    7,    2,    2,    2,    2,    9,
        2,    5,    5,    5,    5,    6,    5,    7,    7,   10,
        7,    7,    7,    7,    7,    8,    7,    7,    7,    7,
        7,    7,    7,    7,    2,    2,    2
    } ;

static const flex_int16_t yy_base[441] =
    {   0,
        0,    0, 1177, 1178, 1178, 1178, 1178, 1145, 1144,   69,
     1127, 1178, 1178,   61,   66, 1178,   65,   82,   80,  102,
       93, 1142, 1178,  101, 1141,   51,  157, 1178, 1178, 1140,
        0,  166,   24,   98,   29,   71,  104,   21,  137,   78,
       88,   79,   99,  143,  142,   46,   28,  107, 1178,  166,
     1178, 1178, 1178, 1178, 1178, 1139, 1159,  237, 1178, 1178,
     1178, 1178, 1178, 1178, 1151,  165, 1178, 1178, 1178,  167,
      294,  189,   96,  249,  303,  155,  313, 1178,  227,  336,
     1178, 1178, 1136, 1178, 1178, 1178, 1135, 1115, 1098, 1113,
     1178, 1112, 1095,  102,   48,  154,  156,  167,  163,  171,

      174,  180,  184,  216,  187,  188,  215,  172, 1094,  233,
      222,  229,  231,  146,  232,  236,  312,  239,  279,  200,
      282, 1093,  283,  263, 1178, 1146, 1178, 1178, 1178, 1147,
     1146,  348,    0,    0,    0, 1178,  337,  380,  389,  380,
      423,    0,  399,  432,  332,  356,  441,  450,  459,  466,
        0,  475,  329,  476,  523, 1178, 1178,  324,  329,  322,
      325, 1089,  372,  363,  365, 1088,  366,  428,  445,  439,
      440,  433,  441,  452, 1087,  332,  449,  454,  456,  508,
     1086,  461, 1085, 1084,  463,  323,  465,  489,  472,  486,
      497,  501,  499,  243,  502,  504, 1083, 1137,  556,    0,

        0,    0,  563,  572,  563,  582,  614,  623,  601,  520,
      643,  633,  655,  605,  631,  630,  667,  715,  702,  496,
     1081, 1080,  500, 1079, 1078,  626,  548,  546,  551, 1077,
      619,  505,  621, 1076,  628,  622,  632, 1075, 1074, 1073,
      633,  661,  695,  697, 1088,  640, 1071,  646,  655,  648,
     1070,  647,  656, 1069,  678,  552,  692,  694, 1068,  729,
      699, 1123,    0,    0,  756,  765,  777,  788,  776,  778,
      779,  827,  836,  695, 1066, 1065,  697, 1064,  660,  703,
     1063,  700, 1062,   82,  799,  659, 1077, 1076, 1075,  707,
      701, 1058, 1057,  766,  706,  764,  765,  773,  759,  816,

      814,  707, 1072,  774, 1046, 1077,    0,    0,  826,  827,
      878,  887, 1053,  805,  803,  806, 1052,  727,  866,  865,
     1051,  818,  823,  814, 1050, 1049, 1048,  816, 1047, 1062,
     1044, 1033,  824, 1044,  997,    0,  897,  863,  864,  829,
     1001, 1000,  867,  982,  962,  961,  959,  979,  960,    0,
      897,  900,  947,  946,  861,  868,  975,  952,    0,  899,
      955,  874,  938,  963,  933,    0,  947,  876,  956,  937,
      870,  901,  921,  909,  886,  911,  949,  915,  955,  905,
      944,  893,  942,  883,  939,  895,  936,  869,  934,  868,
      892,  866,  861,  892, 1178,  809,  805,  782,  786,  761,

      719,  569,  484,  452,  364,  353,  330,  219,  145,   85,
     1178,  962,  970,  977,  983,  990,  997, 1005, 1013, 1020,
     1027, 1034, 1037, 1040, 1043, 1050, 1054, 1061, 1064, 1067,
     1070, 1076, 1081, 1084, 1087, 1093, 1096, 1099, 1102, 1105
    } ;

static const flex_int16_t yy_def[441] =
    {   0,
      411,    1,  411,  411,  411,  411,  411,  411,  411,  411,
      412,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      413,  411,  411,  411,  411,  411,  414,  411,  411,  411,
      415,  414,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  416,  411,  411,  411,  417,
      411,  418,  411,  411,  411,  419,  411,  411,  420,  411,
      411,  411,  411,  411,  411,  411,  411,  421,   32,  421,
      411,  421,   32,   32,   32,   32,   32,   32,   32,   32,

       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,  411,  411,  411,  411,  411,  411,
      411,  411,  422,  423,  424,  411,  416,  411,  411,  425,
      411,   71,  411,  411,  411,  411,  411,  411,  411,  411,
      426,  427,  419,  420,  411,  411,  411,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,  411,  411,  428,

      429,  430,  411,  411,  425,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  431,  432,  427,  411,  427,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,  421,  421,  421,  421,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
      411,  411,  433,  434,  411,  411,  411,  411,  431,  431,
      435,  411,  411,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,  421,  421,  421,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,  421,

      421,  421,  421,   32,  411,  411,  436,  437,  435,  435,
      411,  411,   32,   32,   32,   32,   32,   32,  421,  421,
       32,   32,   32,   32,   32,   32,   32,   32,   32,  421,
      421,  421,   32,  411,  411,  438,   32,   32,   32,   32,
      421,  421,   32,   32,   32,   32,   32,  411,  411,  439,
      421,  421,   32,   32,   32,   32,  411,  411,  440,  421,
      421,   32,   32,  411,  411,  437,  421,   32,  411,  411,
       32,  411,  411,   32,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
        0,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411
    } ;

static const flex_int16_t yy_nxt[1256] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   28,    4,   29,   30,   31,
        4,   32,   33,   34,   35,   36,   37,   38,   27,   39,
       27,   40,   41,   42,   27,   43,   44,   45,   46,   47,
       48,   27,   27,   27,   49,   50,   51,   54,   59,   61,
       63,   86,   87,   94,  101,  108,   89,  123,   95,   89,
       96,   60,   67,   89,   89,   64,   62,   68,   65,   55,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   70,
       69,   89,  160,   89,  145,  145,   82,   56,   70,  122,
       71,   71,   71,   71,   71,   71,   71,   72,   72,   74,
       83,   84,  102,  112,  114,   73,   89,  103,   74,  113,
      318,   75,   80,   89,   89,  146,   76,   89,   74,   97,
      115,   77,   78,   89,   73,  104,   98,   74,  124,   99,
      395,   78,  100,   89,   89,  105,   75,   89,  106,   89,
      159,  151,   89,  107,   76,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,  109,  116,  410,  125,  119,  117,  110,

      111,  138,   89,  141,  153,   70,   90,   89,   89,  161,
      120,   89,  118,  121,  139,   90,  126,  184,  164,   89,
      138,  162,  141,  163,   78,   74,   78,  165,   89,  409,
      169,   93,   89,  166,  167,  170,  168,   89,  144,   89,
      177,  127,  130,   70,   74,   89,  131,  171,   78,   89,
      172,  174,   89,   89,  175,  132,  132,  132,  132,  132,
      132,  132,  147,   74,  147,   89,  193,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  155,  173,  176,  133,
       89,   89,   74,  130,  178,  185,   78,   89,  130,  130,
      180,  182,  181,  130,   89,  186,  183,   89,  179,  187,

      130,   89,  191,  130,   89,  130,  134,  130,   89,  135,
       70,  258,  142,  142,  142,  142,  142,  142,  142,   72,
       72,  149,  149,  149,  149,  149,  149,  149,   89,  197,
       74,   71,   71,   71,   71,   71,   71,   71,   72,   72,
      192,  194,  408,  143,   89,  411,  196,   89,   89,   74,
      209,  209,  150,   78,   79,   79,   79,   79,   79,   79,
       79,   79,   79,  188,  407,  189,  199,  199,  199,  199,
      199,  199,  199,  138,  145,  145,  223,   89,  411,  220,
      190,  210,  249,  222,  221,  238,  139,   89,   89,   89,
       89,   78,  138,  203,   89,  203,   78,   89,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  137,  137,  137,
      137,  137,  137,  137,  137,  137,  141,  142,  142,  142,
      142,  142,  142,  142,   72,   72,  225,  224,   89,  206,
       89,   89,  226,  228,  229,  141,  207,   89,  207,   78,
      406,  208,  208,  208,  208,  208,  208,  208,  208,  208,
       72,   72,   72,   72,   72,   72,   72,   72,   72,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  211,  211,
      211,  211,  211,  211,  211,  211,  211,  213,  213,  213,
      213,  213,  213,  213,  149,  149,  149,  149,  149,  149,
      149,  216,   70,   89,  233,  234,  231,  235,   89,  212,

      232,  230,  236,  237,   89,   89,   89,  405,  214,   78,
       89,  240,   74,  239,   89,  218,  247,   89,   78,   89,
      241,   89,  250,  248,  219,  155,   89,  242,   89,  243,
       89,   74,  244,  245,   78,   78,  252,   89,  209,  209,
      218,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      251,   89,  254,  404,   89,  253,  255,  259,  256,  274,
      275,   89,   89,  246,   89,   89,   89,   89,  257,   89,
       89,  281,  260,   89,  262,  262,  262,  262,  262,  262,
      262,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  141,

      205,  205,  205,  205,  205,  205,  205,  205,  205,  277,
      279,   89,  206,   89,  278,  297,   89,   89,  141,  209,
      209,  266,   78,  213,  213,  213,  213,  213,  213,  213,
      403,   78,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  267,  267,  267,  267,  267,  267,  267,  267,  267,
      210,  211,  211,  211,  211,  211,  211,  211,  211,  211,
       78,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      218,  218,  268,  213,  213,  213,  213,  213,  213,  213,
      270,  276,   78,  216,   89,  287,   89,   89,  280,  282,
      284,   89,  212,   89,  283,  218,  218,   89,   89,  286,

      285,  291,   78,  293,  214,   89,  290,  218,  292,  305,
       90,   89,   89,   89,   78,  288,  219,  294,  411,  289,
       89,   89,  295,  315,   89,   89,   78,  321,  272,  332,
      272,  296,  218,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  411,   89,   90,  298,   90,  299,  300,  313,
      301,  411,  314,  302,  303,  317,   90,   89,  323,   89,
       89,  411,   89,  322,  316,   89,   89,  411,   89,  325,
      402,   89,   89,  306,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,   89,  340,  304,  267,  267,  267,  267,  267,

      267,  267,  267,  267,  401,  266,  267,  267,  267,  267,
      267,  267,  267,  267,  267,   78,  218,  329,  411,  218,
      319,  324,  327,  320,   89,  270,  268,  411,  310,   89,
       89,   89,  326,  328,  331,  400,   78,  399,   89,   89,
      330,  218,  333,  411,  218,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  311,  311,  311,  311,  311,  311,
      311,  311,  311,   90,   89,   90,  218,  411,   89,  343,
       89,   89,  338,  398,  339,  310,  411,  337,  344,   89,
      345,   89,  397,   89,  346,  312,  341,  342,   89,   89,
      347,  218,  411,  355,   89,   78,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,   90,   90,  351,  360,  353,  354,
      356,  352,  361,  363,  367,  396,   89,  312,   89,   89,
      362,  368,   89,   89,  371,   89,  395,   78,  374,   89,
      394,   89,  393,  392,  391,  390,   90,  389,   90,   90,
      388,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  377,   89,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   79,   79,   89,   79,  376,  375,   79,   79,
       89,   89,   89,   89,   89,   89,   89,   92,   92,   92,
       92,  373,   92,  137,  372,  137,   90,  370,  137,  137,

      140,  369,  140,   89,   90,  365,  140,   72,   72,  364,
       72,   89,   89,   72,   72,  152,  152,  152,  152,  358,
      357,  152,  154,  154,   89,  154,   89,   89,  154,  154,
       88,   88,   88,   88,   88,   88,   88,  200,  200,  200,
      201,  201,  201,  202,  202,  202,  205,   89,  205,   90,
       90,  205,  205,  215,  215,  215,  217,  217,  217,  217,
      349,  217,  217,  217,  263,  263,  263,  264,  264,  264,
      262,  262,  262,  269,  269,  269,  348,  269,  269,  271,
      271,  271,   90,  271,  307,  307,  307,  308,  308,  308,
      309,  309,  309,   90,  309,  309,  336,  336,  336,   57,

       57,   57,  350,  350,  350,  359,  359,  359,  366,  366,
      366,   90,   89,   89,   89,   89,   89,   89,   89,  335,
      334,   90,   89,   89,   90,   90,   90,   89,   89,   89,
       89,   89,  129,   89,   89,   89,   89,   90,   89,   89,
       89,   89,   89,   89,   89,   89,   89,  261,   89,   89,
       89,   89,   89,  227,   89,  129,  129,  198,  195,   89,
      158,   90,   90,   89,   90,  157,  156,  136,  129,  128,
       91,   85,   81,   58,   53,   52,  411,    3,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411
    } ;

static const flex_int16_t yy_chk[1256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   10,   14,   15,
       17,   26,   26,   33,   35,   38,   38,   47,   33,   33,
       33,   14,   19,   47,   35,   17,   15,   19,   18,   10,

       18,   18,   18,   18,   18,   18,   18,   18,   18,   21,
       19,   46,   95,   95,   73,   73,   24,   10,   20,   46,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   21,
       24,   24,   36,   40,   42,   20,   36,   36,   20,   41,
      284,   20,   21,   40,   42,   73,   20,  284,   21,   34,
       43,   20,   21,   41,   20,   37,   34,   20,   48,   34,
      410,   20,   34,   34,   43,   37,   20,   94,   37,   37,
       94,   76,   48,   37,   20,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   39,   44,  409,   50,   45,   44,   39,

       39,   66,   39,   70,   76,   72,   27,   45,   44,   96,
       45,  114,   44,   45,   66,   32,   50,  114,   98,   96,
       66,   97,   70,   97,   66,   72,   70,   99,   99,  408,
      101,   32,   98,  100,  100,  101,  100,  108,   72,  101,
      108,   50,   58,   79,   72,  102,   58,  102,   72,  103,
      103,  105,  105,  106,  106,   58,   58,   58,   58,   58,
       58,   58,   74,   79,   74,  120,  120,   74,   74,   74,
       74,   74,   74,   74,   74,   74,   79,  104,  107,   58,
      107,  104,   79,   58,  110,  115,   79,  111,   58,   58,
      111,  113,  112,   58,  112,  115,  113,  115,  110,  116,

       58,  116,  118,   58,  118,   58,   58,   58,  194,   58,
       71,  194,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   75,   75,   75,   75,   75,   75,   75,  124,  124,
       71,   77,   77,   77,   77,   77,   77,   77,   77,   77,
      119,  121,  407,   71,  119,  153,  123,  121,  123,   71,
      145,  145,   75,   71,   80,   80,   80,   80,   80,   80,
       80,   80,   80,  117,  406,  117,  132,  132,  132,  132,
      132,  132,  132,  137,  146,  146,  161,  117,  153,  158,
      117,  145,  186,  160,  159,  176,  137,  160,  186,  158,
      161,  145,  137,  138,  159,  138,  137,  176,  138,  138,

      138,  138,  138,  138,  138,  138,  138,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  140,  143,  143,  143,
      143,  143,  143,  143,  143,  143,  164,  163,  164,  140,
      165,  167,  165,  167,  167,  140,  141,  163,  141,  140,
      405,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  149,  149,  149,
      149,  149,  149,  149,  150,  150,  150,  150,  150,  150,
      150,  152,  154,  168,  170,  171,  169,  172,  172,  148,

      169,  168,  173,  174,  170,  171,  173,  404,  149,  148,
      169,  178,  154,  177,  177,  152,  182,  174,  149,  178,
      179,  179,  187,  185,  152,  154,  182,  180,  185,  180,
      187,  154,  180,  180,  152,  154,  189,  189,  210,  210,
      152,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      188,  190,  191,  403,  188,  190,  192,  195,  193,  220,
      223,  220,  191,  180,  193,  223,  192,  195,  193,  196,
      232,  232,  196,  180,  199,  199,  199,  199,  199,  199,
      199,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  205,

      206,  206,  206,  206,  206,  206,  206,  206,  206,  227,
      229,  228,  205,  227,  228,  256,  229,  256,  205,  209,
      209,  204,  205,  214,  214,  214,  214,  214,  214,  214,
      402,  204,  207,  207,  207,  207,  207,  207,  207,  207,
      207,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      209,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      209,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      216,  215,  208,  213,  213,  213,  213,  213,  213,  213,
      215,  226,  208,  217,  231,  242,  233,  236,  231,  233,
      236,  226,  211,  235,  235,  216,  215,  237,  241,  241,

      237,  248,  211,  250,  213,  246,  246,  217,  249,  261,
      242,  248,  252,  250,  213,  243,  217,  252,  219,  244,
      249,  253,  253,  279,  286,  279,  217,  286,  218,  302,
      218,  255,  217,  218,  218,  218,  218,  218,  218,  218,
      218,  218,  219,  255,  243,  257,  244,  258,  260,  274,
      260,  219,  277,  260,  260,  282,  302,  257,  291,  258,
      274,  219,  277,  290,  280,  282,  291,  219,  280,  295,
      401,  295,  290,  261,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  318,  318,  260,  267,  267,  267,  267,  267,

      267,  267,  267,  267,  400,  265,  268,  268,  268,  268,
      268,  268,  268,  268,  268,  265,  269,  299,  270,  271,
      285,  294,  297,  285,  299,  269,  267,  270,  271,  296,
      297,  294,  296,  298,  301,  399,  267,  398,  298,  304,
      300,  269,  304,  270,  271,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  301,  285,  300,  309,  310,  315,  322,
      314,  316,  315,  397,  316,  309,  310,  314,  323,  324,
      324,  328,  396,  322,  328,  273,  319,  320,  323,  333,
      333,  309,  310,  340,  340,  273,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  320,  319,  337,  351,  338,  339,
      343,  337,  352,  356,  360,  394,  355,  311,  338,  339,
      355,  362,  343,  356,  368,  371,  393,  311,  371,  362,
      392,  368,  391,  390,  389,  388,  351,  387,  360,  352,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  337,  412,  412,  412,  412,  412,  412,  412,
      412,  412,  413,  413,  374,  413,  373,  372,  413,  413,
      414,  414,  414,  414,  414,  414,  414,  415,  415,  415,
      415,  370,  415,  416,  369,  416,  367,  365,  416,  416,

      417,  364,  417,  363,  361,  358,  417,  418,  418,  357,
      418,  354,  353,  418,  418,  419,  419,  419,  419,  349,
      348,  419,  420,  420,  347,  420,  346,  345,  420,  420,
      421,  421,  421,  421,  421,  421,  421,  422,  422,  422,
      423,  423,  423,  424,  424,  424,  425,  344,  425,  342,
      341,  425,  425,  426,  426,  426,  427,  427,  427,  427,
      335,  427,  427,  427,  428,  428,  428,  429,  429,  429,
      430,  430,  430,  431,  431,  431,  334,  431,  431,  432,
      432,  432,  332,  432,  433,  433,  433,  434,  434,  434,
      435,  435,  435,  331,  435,  435,  436,  436,  436,  437,

      437,  437,  438,  438,  438,  439,  439,  439,  440,  440,
      440,  330,  329,  327,  326,  325,  321,  317,  313,  306,
      305,  303,  293,  292,  289,  288,  287,  283,  281,  278,
      276,  275,  262,  259,  254,  251,  247,  245,  240,  239,
      238,  234,  230,  225,  224,  222,  221,  198,  197,  184,
      183,  181,  175,  166,  162,  131,  130,  126,  122,  109,
       93,   92,   90,   89,   88,   87,   83,   65,   57,   56,
       30,   25,   22,   11,    9,    8,    3,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Analyser.l"
#line 2 "Analyser.l"
//#include "syntax.tab.h" //include bison's header file
//#include "syntax.tab.c" //include bison's .c file...not sure
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

//used in error function
FILE *fd; //a global copy of the input file -- accessible from error funtion
int line_no = 1;
int errors = 0;

char strbuffer[200];//a string buffer to properly return strings
char *ptr; //used in strtol function
int doubletoint; //convert double to int


//#include "hashtbl.h" //include the hash table
//extern HASHTBL *symbol; //Symbol Table declaration (global)

/*antistoixhsh lektikwn monadwn (telikwn katastasewn) me ari8mous - kwdikoys eksodoy*/


void ERROR (const char msg [], char *text); //synarthsh epistrofis la8oys
double decRealHandler(char *str); //convert string to real
double hexRealHandler(char *str); //conver hex real string to real
#line 887 "lex.yy.c"
/* Integer literals*/
/* floating piont literals*/
/* Imaginary literals*/
/*Rune literals*/
/*String Literal*/
#line 893 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 116 "Analyser.l"


#line 1113 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 412 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1178 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 118 "Analyser.l"
{printf("  T_BREAK");}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 119 "Analyser.l"
{printf("  T_CASE");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 120 "Analyser.l"
{printf("  T_CHAN");}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 121 "Analyser.l"
{printf("  T_CONST");}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 122 "Analyser.l"
{printf("  T_CONTINUE");}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 123 "Analyser.l"
{printf("  T_DEFAULT");}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 124 "Analyser.l"
{printf("  T_DEFER");}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 125 "Analyser.l"
{printf("  T_ELSE");}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 126 "Analyser.l"
{printf("  T_FALLTHROUGH");}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 127 "Analyser.l"
{printf("  T_FOR");}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 128 "Analyser.l"
{printf("  T_FUNC");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 129 "Analyser.l"
{printf("  T_GO");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 130 "Analyser.l"
{printf("  T_GOTO");}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 131 "Analyser.l"
{printf("  T_IF");}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 132 "Analyser.l"
{printf("  T_IMPORT");}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 133 "Analyser.l"
{printf("  T_INTERFACE");}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 134 "Analyser.l"
{printf("  T_MAP");}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 135 "Analyser.l"
{printf("  T_PACKAGE");}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 136 "Analyser.l"
{printf("  T_RANGE");}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 137 "Analyser.l"
{printf("  T_RETURN");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 138 "Analyser.l"
{printf("  T_SELECT");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 139 "Analyser.l"
{printf("  T_STRUCKT");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 140 "Analyser.l"
{printf("  T_SWITCH");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 141 "Analyser.l"
{printf("  T_TYPE");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 142 "Analyser.l"
{printf("  T_VAR");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 144 "Analyser.l"
{printf("  T_INT");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 145 "Analyser.l"
{printf("  T_INT8");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 146 "Analyser.l"
{printf("  T_INT16");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 147 "Analyser.l"
{printf("  T_INT32");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 148 "Analyser.l"
{printf("  T_INT64");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 149 "Analyser.l"
{printf("  T_UINT");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 150 "Analyser.l"
{printf("  T_UINT8");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 151 "Analyser.l"
{printf("  T_UINT16");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 152 "Analyser.l"
{printf("  T_UINT32");}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 153 "Analyser.l"
{printf("  T_UINT64");}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 154 "Analyser.l"
{printf("  T_UINTPTR");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 155 "Analyser.l"
{printf("  T_FLOAT32");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 156 "Analyser.l"
{printf("  T_FLOAT64");}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 157 "Analyser.l"
{printf("  T_COMPLEX64");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 158 "Analyser.l"
{printf("  T_COMPLEX128");}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 159 "Analyser.l"
{printf("  T_BOOL");}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 160 "Analyser.l"
{printf("  T_BITE");}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 161 "Analyser.l"
{printf("  T_RUNE");}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 162 "Analyser.l"
{printf("  T_STRING");}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 163 "Analyser.l"
{printf("  T_ERROR");}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 165 "Analyser.l"
{printf("  T_MAKE");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 166 "Analyser.l"
{printf("  T_LEN");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 167 "Analyser.l"
{printf("  T_CAP");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 168 "Analyser.l"
{printf("  T_NEW");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 169 "Analyser.l"
{printf("  T_APPEND");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 170 "Analyser.l"
{printf("  T_COPY");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 171 "Analyser.l"
{printf("  T_CLOSE");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 172 "Analyser.l"
{printf("  T_DELETE");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 173 "Analyser.l"
{printf("  T_COMPLEX");}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 174 "Analyser.l"
{printf("  T_REAL");}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 175 "Analyser.l"
{printf("  T_IMAG");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 176 "Analyser.l"
{printf("  T_PANIC");}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 177 "Analyser.l"
{printf("  T_RECOVER");}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 179 "Analyser.l"
{printf("  T_LESS");}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 180 "Analyser.l"
{printf("  T_GREAT");}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 181 "Analyser.l"
{printf("  T_LESSOREQU");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 182 "Analyser.l"
{printf("  T_GREATOREQU");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 183 "Analyser.l"
{printf("  T_NOTEQU");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 184 "Analyser.l"
{printf("  T_EQU");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 186 "Analyser.l"
{printf("  T_ANDOP");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 187 "Analyser.l"
{printf("  T_OROP");}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 188 "Analyser.l"
{printf("  T_NOTOP");}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 190 "Analyser.l"
{printf("   T_ADDOP ");}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 191 "Analyser.l"
{printf("   T_MULTOP ");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 192 "Analyser.l"
{printf("   T_SUBTROP ");}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 193 "Analyser.l"
{printf("   T_DIVOP ");}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 194 "Analyser.l"
{printf("   T_MOD ");}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 195 "Analyser.l"
{printf("   T_ADDASSOP ");}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 196 "Analyser.l"
{printf("   T_MULTASSOP  ");}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 197 "Analyser.l"
{printf("   T_SUBTRASSOP  ");}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 198 "Analyser.l"
{printf("   T_DIVASSOP ");}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 200 "Analyser.l"
{printf("   T_DOUBLEPLUSOP ");}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 201 "Analyser.l"
{printf("   T_DOUBLEMINUSOP ");}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 203 "Analyser.l"
{line_no++; printf("   T_NL\n"); printf("%d)", line_no); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 204 "Analyser.l"
{printf("   T_TAB ");}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 206 "Analyser.l"
{printf("   T_REFERENCE ");}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 208 "Analyser.l"
{printf("   T_LCURLYBR ");}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 209 "Analyser.l"
{printf("   T_RCURLYBR ");}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 210 "Analyser.l"
{printf("   T_LPAREN ");}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 211 "Analyser.l"
{printf("   T_RPAREN ");}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 212 "Analyser.l"
{printf("   T_LBRACK ");}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 213 "Analyser.l"
{printf("   T_RBRACK ");}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 215 "Analyser.l"
{printf("   T_SEMI ");}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 216 "Analyser.l"
{printf("   T_DOT ");}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 217 "Analyser.l"
{printf("   T_COMMA ");}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 218 "Analyser.l"
{printf("   T_COLON ");}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 219 "Analyser.l"
{printf("   T_ASSIGN ");}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 220 "Analyser.l"
{printf("   T_ASSIGNOP ");}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 221 "Analyser.l"
{printf("   T_DOTDOTDOT ");}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 222 "Analyser.l"
{printf("   T_SIMPLCOMMENT ");}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 223 "Analyser.l"
{printf("   T_LBLOCKCOMMET ");}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 224 "Analyser.l"
{printf("   T_RBLOCKCOMMET ");}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 226 "Analyser.l"
{printf("   T_BITOR ");}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 227 "Analyser.l"
{printf("   T_XOR ");}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 228 "Analyser.l"
{printf("   T_LSHIFT ");}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 229 "Analyser.l"
{printf("   T_RSHIFT ");}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 230 "Analyser.l"
{printf("   T_BITCLEAR ");}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 231 "Analyser.l"
{printf("   T_MODEQUOP ");}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 232 "Analyser.l"
{printf("   T_ANDEQUOP ");}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 233 "Analyser.l"
{printf("   T_OREQUOP ");}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 234 "Analyser.l"
{printf("   T_XOREQUOP ");}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 235 "Analyser.l"
{printf("   T_LSHIFTEQU ");}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 236 "Analyser.l"
{printf("   T_RSHIFTEQU ");}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 237 "Analyser.l"
{printf("   T_BITCLEAREQU ");}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 238 "Analyser.l"
{printf("   T_SENDOP ");}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 241 "Analyser.l"
{ /*yylval.string = strdup(yytext);*/ printf("   T_ID");} //ID _hashtbl_insert(symbol,yytext,NULL,0);
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 243 "Analyser.l"
{printf("   T_ICONST");}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 244 "Analyser.l"
{printf("   T_RCONST");}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 245 "Analyser.l"
{printf("   T_IMCONST");}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 246 "Analyser.l"
{printf("   T_CCONST");}
	YY_BREAK
case 116:
/* rule 116 can match eol */
YY_RULE_SETUP
#line 247 "Analyser.l"
{printf("   T_SCONST");}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 249 "Analyser.l"
{}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 250 "Analyser.l"
{printf("   Printing unexpected character");}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 252 "Analyser.l"
ECHO;
	YY_BREAK
#line 1767 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 412 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 412 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 411);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 252 "Analyser.l"

void ERROR (const char msg [], char *text) {
    /* code to print the erroneous line
    reopen input file and print the line that corresponds to line_no -> number of the line that the error occured*/
    int end, loop; 
    char str[512];

    if (fd == NULL) {printf("Failed to open file\n");}

    for(end = loop = 0;loop<line_no;++loop){
        if(0==fgets(str, sizeof(str), fd)){//include '\n'
            end = 1;//can't input (EOF)
            break;
        }
    }
    fprintf(stderr, "\n LEXIXAL ERROR at line %d. Error type: %s. Error line: %sTotal errors: %d \n",line_no, msg,str,errors);
    fclose(fd);
    if (errors>1) {
    printf("More than one **Lexical** errors!--early termination\n");
    exit(1);}
}
